import { z } from "zod";
import {
	AiAttachmentWriteMsgSchema,
	AiSessionCloseMsgSchema,
	AiSessionConfigSetMsgSchema,
	AiSessionForkMsgSchema,
	AiSessionLoadMsgSchema,
	AiSessionModelSetMsgSchema,
	AiSessionModeSetMsgSchema,
	AiSessionResumeMsgSchema,
} from "@/agents";
import {
	AiAbortMsgSchema,
	AiActivityListMsgSchema,
	AiAgentsListMsgSchema,
	AiAuthSetMsgSchema,
	AiAvailabilityMsgSchema,
	AiCommandMsgSchema,
	AiMessagesListMsgSchema,
	AiPermissionReplyMsgSchema,
	AiPromptMsgSchema,
	AiProvidersListMsgSchema,
	AiQuestionRejectMsgSchema,
	AiQuestionReplyMsgSchema,
	AiRevertMsgSchema,
	AiSessionCreateMsgSchema,
	AiSessionDeleteMsgSchema,
	AiSessionGetMsgSchema,
	AiSessionListMsgSchema,
	AiShareMsgSchema,
	AiUnrevertMsgSchema,
} from "@/ai-legacy";
import { PongMsgSchema } from "@/base";
import {
	FsDeleteMsgSchema,
	FsListMsgSchema,
	FsMkdirMsgSchema,
	FsReadMsgSchema,
	FsRenameMsgSchema,
	FsStatMsgSchema,
	FsWriteMsgSchema,
	GitReadMsgSchema,
	ProjectFileSearchMsgSchema,
	ProjectInfoMsgSchema,
} from "@/filesystem";
import {
	HttpRequestMsgSchema,
	WsCloseMsgSchema,
	WsDataMsgSchema,
	WsOpenMsgSchema,
} from "@/http";
import { PortsKillMsgSchema, PortsListMsgSchema } from "@/ports";
import { SysmonGetMsgSchema } from "@/sysmon";
import {
	TerminalAttachMsgSchema,
	TerminalCloseMsgSchema,
	TerminalCreateMsgSchema,
	TerminalDataMsgSchema,
	TerminalListMsgSchema,
	TerminalResizeMsgSchema,
} from "@/terminal";

export const ClientToHostMsgSchema = z.discriminatedUnion("type", [
	TerminalCreateMsgSchema,
	TerminalListMsgSchema,
	TerminalAttachMsgSchema,
	TerminalDataMsgSchema,
	TerminalResizeMsgSchema,
	TerminalCloseMsgSchema,
	FsListMsgSchema,
	FsReadMsgSchema,
	FsWriteMsgSchema,
	FsMkdirMsgSchema,
	FsDeleteMsgSchema,
	FsRenameMsgSchema,
	FsStatMsgSchema,
	SysmonGetMsgSchema,
	HttpRequestMsgSchema,
	WsOpenMsgSchema,
	WsDataMsgSchema,
	WsCloseMsgSchema,
	PongMsgSchema,
	PortsListMsgSchema,
	PortsKillMsgSchema,
	ProjectInfoMsgSchema,
	ProjectFileSearchMsgSchema,
	GitReadMsgSchema,
	AiAvailabilityMsgSchema,
	AiSessionListMsgSchema,
	AiSessionCreateMsgSchema,
	AiSessionLoadMsgSchema,
	AiSessionResumeMsgSchema,
	AiSessionForkMsgSchema,
	AiSessionCloseMsgSchema,
	AiSessionGetMsgSchema,
	AiSessionDeleteMsgSchema,
	AiMessagesListMsgSchema,
	AiPromptMsgSchema,
	AiAttachmentWriteMsgSchema,
	AiSessionConfigSetMsgSchema,
	AiSessionModeSetMsgSchema,
	AiSessionModelSetMsgSchema,
	AiAbortMsgSchema,
	AiActivityListMsgSchema,
	AiAgentsListMsgSchema,
	AiProvidersListMsgSchema,
	AiAuthSetMsgSchema,
	AiCommandMsgSchema,
	AiRevertMsgSchema,
	AiUnrevertMsgSchema,
	AiShareMsgSchema,
	AiPermissionReplyMsgSchema,
	AiQuestionReplyMsgSchema,
	AiQuestionRejectMsgSchema,
]);

export type ClientToHostMsg = z.infer<typeof ClientToHostMsgSchema>;
