import { z } from "zod";
import {
	AiAgentsCustomAddResultMsgSchema,
	AiAgentsCustomRemoveResultMsgSchema,
	AiAgentsCustomUpdateResultMsgSchema,
	AiAgentsEnableSetResultMsgSchema,
	AiAgentsManageListResultMsgSchema,
	AiAttachmentWriteResultMsgSchema,
	AiPromptQueuePauseAckMsgSchema,
	AiPromptQueueRemoveAckMsgSchema,
	AiPromptQueueUpdateAckMsgSchema,
	AiSessionAttachResultMsgSchema,
	AiSessionCloseResultMsgSchema,
	AiSessionConfigSetResultMsgSchema,
	AiSessionDetachResultMsgSchema,
	AiSessionForkResultMsgSchema,
	AiSessionModeSetResultMsgSchema,
	AiSessionResumeResultMsgSchema,
} from "@/agents";
import {
	AiAbortAckMsgSchema,
	AiActivityDismissResultMsgSchema,
	AiActivityListResultMsgSchema,
	AiAgentsListResultMsgSchema,
	AiAuthSetAckMsgSchema,
	AiCommandResultMsgSchema,
	AiElicitationReplyAckMsgSchema,
	AiEventMsgSchema,
	AiMessagesListResultMsgSchema,
	AiPermissionReplyAckMsgSchema,
	AiPromptAckMsgSchema,
	AiProvidersListResultMsgSchema,
	AiQuestionRejectAckMsgSchema,
	AiQuestionReplyAckMsgSchema,
	AiRevertAckMsgSchema,
	AiSessionCreateResultMsgSchema,
	AiSessionDeletedMsgSchema,
	AiSessionGetResultMsgSchema,
	AiSessionListResultMsgSchema,
	AiSessionOwnerKillResultMsgSchema,
	AiShareResultMsgSchema,
	AiUnrevertAckMsgSchema,
} from "@/ai-legacy";
import {
	FsListResultMsgSchema,
	FsReadResultMsgSchema,
	FsResultMsgSchema,
	FsStatResultMsgSchema,
	FsWriteResultMsgSchema,
	GitCommitFileDiffResultMsgSchema,
	GitCommitFilesResultMsgSchema,
	GitLogResultMsgSchema,
	GitOperationResultMsgSchema,
	GitReadResultMsgSchema,
	ProjectFileSearchResultMsgSchema,
	ProjectInfoResultMsgSchema,
} from "@/filesystem";
import { HostUpdateResultMsgSchema } from "@/host/update";
import {
	HttpResponseDataMsgSchema,
	HttpResponseEndMsgSchema,
	HttpResponseStartMsgSchema,
	WsClosedMsgSchema,
	WsDataMsgSchema,
	WsOpenedMsgSchema,
} from "@/http";
import { PortsKillResultMsgSchema, PortsListResultMsgSchema } from "@/ports";
import { BatteryUpdateMsgSchema, SysmonResultMsgSchema } from "@/sysmon";
import {
	TerminalAttachResultMsgSchema,
	TerminalClosedMsgSchema,
	TerminalCreateResultMsgSchema,
	TerminalListResultMsgSchema,
	TerminalOutputMsgSchema,
	TerminalTitleMsgSchema,
} from "@/terminal";

export const HostToClientSchema = z.discriminatedUnion("type", [
	TerminalCreateResultMsgSchema,
	TerminalListResultMsgSchema,
	TerminalAttachResultMsgSchema,
	TerminalOutputMsgSchema,
	TerminalClosedMsgSchema,
	TerminalTitleMsgSchema,
	FsResultMsgSchema,
	FsListResultMsgSchema,
	FsReadResultMsgSchema,
	FsWriteResultMsgSchema,
	FsStatResultMsgSchema,
	SysmonResultMsgSchema,
	BatteryUpdateMsgSchema,
	HttpResponseStartMsgSchema,
	HttpResponseDataMsgSchema,
	HttpResponseEndMsgSchema,
	WsOpenedMsgSchema,
	WsDataMsgSchema,
	WsClosedMsgSchema,
	PortsListResultMsgSchema,
	PortsKillResultMsgSchema,
	ProjectInfoResultMsgSchema,
	ProjectFileSearchResultMsgSchema,
	GitReadResultMsgSchema,
	GitLogResultMsgSchema,
	GitCommitFilesResultMsgSchema,
	GitCommitFileDiffResultMsgSchema,
	GitOperationResultMsgSchema,
	AiSessionListResultMsgSchema,
	AiSessionCreateResultMsgSchema,
	AiSessionAttachResultMsgSchema,
	AiSessionDetachResultMsgSchema,
	AiSessionResumeResultMsgSchema,
	AiSessionForkResultMsgSchema,
	AiSessionCloseResultMsgSchema,
	AiSessionGetResultMsgSchema,
	AiSessionDeletedMsgSchema,
	AiMessagesListResultMsgSchema,
	AiPromptAckMsgSchema,
	AiPromptQueueUpdateAckMsgSchema,
	AiPromptQueueRemoveAckMsgSchema,
	AiPromptQueuePauseAckMsgSchema,
	AiAttachmentWriteResultMsgSchema,
	AiSessionConfigSetResultMsgSchema,
	AiSessionModeSetResultMsgSchema,
	AiAbortAckMsgSchema,
	AiSessionOwnerKillResultMsgSchema,
	AiActivityDismissResultMsgSchema,
	AiActivityListResultMsgSchema,
	AiAgentsListResultMsgSchema,
	AiAgentsManageListResultMsgSchema,
	AiAgentsEnableSetResultMsgSchema,
	AiAgentsCustomAddResultMsgSchema,
	AiAgentsCustomUpdateResultMsgSchema,
	AiAgentsCustomRemoveResultMsgSchema,
	AiProvidersListResultMsgSchema,
	AiAuthSetAckMsgSchema,
	AiCommandResultMsgSchema,
	AiRevertAckMsgSchema,
	AiUnrevertAckMsgSchema,
	AiShareResultMsgSchema,
	AiPermissionReplyAckMsgSchema,
	AiElicitationReplyAckMsgSchema,
	AiQuestionReplyAckMsgSchema,
	AiQuestionRejectAckMsgSchema,
	AiEventMsgSchema,
	HostUpdateResultMsgSchema,
]);

export type HostToClientMsg = z.infer<typeof HostToClientSchema>;
