import { z } from "zod";
import {
	AiSessionCloseResultMsgSchema,
	AiSessionConfigSetResultMsgSchema,
	AiSessionForkResultMsgSchema,
	AiSessionLoadResultMsgSchema,
	AiSessionModelSetResultMsgSchema,
	AiSessionModeSetResultMsgSchema,
	AiSessionResumeResultMsgSchema,
} from "@/agents";
import {
	AiAbortAckMsgSchema,
	AiAgentsListResultMsgSchema,
	AiAuthSetAckMsgSchema,
	AiAvailabilityResultMsgSchema,
	AiCommandResultMsgSchema,
	AiEventMsgSchema,
	AiMessagesListResultMsgSchema,
	AiPermissionReplyAckMsgSchema,
	AiPromptAckMsgSchema,
	AiProvidersListResultMsgSchema,
	AiQuestionRejectAckMsgSchema,
	AiQuestionReplyAckMsgSchema,
	AiRevertAckMsgSchema,
	AiSessionCreateResultMsgSchema,
	AiSessionDeletedMsgSchema,
	AiSessionGetResultMsgSchema,
	AiSessionListResultMsgSchema,
	AiShareResultMsgSchema,
	AiUnrevertAckMsgSchema,
} from "@/ai-legacy";
import {
	FsAttachmentWriteResultMsgSchema,
	FsListResultMsgSchema,
	FsReadResultMsgSchema,
	FsResultMsgSchema,
	FsStatResultMsgSchema,
	FsWriteResultMsgSchema,
	GitReadResultMsgSchema,
	ProjectFileSearchResultMsgSchema,
	ProjectInfoResultMsgSchema,
} from "@/filesystem";
import {
	HttpResponseDataMsgSchema,
	HttpResponseEndMsgSchema,
	HttpResponseStartMsgSchema,
	WsClosedMsgSchema,
	WsDataMsgSchema,
	WsOpenedMsgSchema,
} from "@/http";
import { PortsKillResultMsgSchema, PortsListResultMsgSchema } from "@/ports";
import { BatteryUpdateMsgSchema, SysmonResultMsgSchema } from "@/sysmon";
import {
	TerminalAttachResultMsgSchema,
	TerminalClosedMsgSchema,
	TerminalCreateResultMsgSchema,
	TerminalListResultMsgSchema,
	TerminalOutputMsgSchema,
	TerminalTitleMsgSchema,
} from "@/terminal";

export const HostToClientSchema = z.discriminatedUnion("type", [
	TerminalCreateResultMsgSchema,
	TerminalListResultMsgSchema,
	TerminalAttachResultMsgSchema,
	TerminalOutputMsgSchema,
	TerminalClosedMsgSchema,
	TerminalTitleMsgSchema,
	FsResultMsgSchema,
	FsListResultMsgSchema,
	FsReadResultMsgSchema,
	FsWriteResultMsgSchema,
	FsAttachmentWriteResultMsgSchema,
	FsStatResultMsgSchema,
	SysmonResultMsgSchema,
	BatteryUpdateMsgSchema,
	HttpResponseStartMsgSchema,
	HttpResponseDataMsgSchema,
	HttpResponseEndMsgSchema,
	WsOpenedMsgSchema,
	WsDataMsgSchema,
	WsClosedMsgSchema,
	PortsListResultMsgSchema,
	PortsKillResultMsgSchema,
	ProjectInfoResultMsgSchema,
	ProjectFileSearchResultMsgSchema,
	GitReadResultMsgSchema,
	AiAvailabilityResultMsgSchema,
	AiSessionListResultMsgSchema,
	AiSessionCreateResultMsgSchema,
	AiSessionLoadResultMsgSchema,
	AiSessionResumeResultMsgSchema,
	AiSessionForkResultMsgSchema,
	AiSessionCloseResultMsgSchema,
	AiSessionGetResultMsgSchema,
	AiSessionDeletedMsgSchema,
	AiMessagesListResultMsgSchema,
	AiPromptAckMsgSchema,
	AiSessionConfigSetResultMsgSchema,
	AiSessionModeSetResultMsgSchema,
	AiSessionModelSetResultMsgSchema,
	AiAbortAckMsgSchema,
	AiAgentsListResultMsgSchema,
	AiProvidersListResultMsgSchema,
	AiAuthSetAckMsgSchema,
	AiCommandResultMsgSchema,
	AiRevertAckMsgSchema,
	AiUnrevertAckMsgSchema,
	AiShareResultMsgSchema,
	AiPermissionReplyAckMsgSchema,
	AiQuestionReplyAckMsgSchema,
	AiQuestionRejectAckMsgSchema,
	AiEventMsgSchema,
]);

export type HostToClientMsg = z.infer<typeof HostToClientSchema>;
